[workspace]
resolver = "3"
members = ["auto-dispatch", "holyrig", "holyrig-client", "holyrig-console", "omnirig", "rig-test"]
default-members = ["holyrig", "holyrig-console"]

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
